# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
# format = """\
# [╭╴](238)$env_var\
# $all[╰─](238)$character"""

format = """\
[┌─](238)$env_var\
[$all└─](238)$character"""
right_format = """$time"""

# Change the default prompt characters
# [character]
# success_symbol = "[](238)"
# error_symbol = "[](238)"
[character]
success_symbol = "[❯](bold green) "
error_symbol = "[✗](bold red) "

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white) '
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)[@](bold yellow)"
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = "[$hostname](white bold) "
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ﴃ "
style = "blue bold"

[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "

[vagrant]
format = "via [ vagrant $version]($style) "

[docker_context]
format = "via [ $context](bold blue) "

[helm]
format = "via [  $version](bold purple) "

[python]
symbol = " "
python_binary = "python3"

[nodejs]
format = "via [ $version](bold green) "
disabled = true

[kubernetes]
format = 'on [  $context\($namespace\)](bold purple) '
disabled = false
#[kubernetes.context_aliases]
# "dev.local.cluster.k8s" = "dev"
# ".*/openshift-cluster/.*" = "openshift"
# "gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "local"
#time_range = "10:00:00-14:00:00"